experiment:
    id: linext

##Data
data:
    data_dir: './KITTI_Odometry/'
    resolution: 0.05
    dataloader: 'KITTI'
    split: 'train'
#    train: [ '00', '01', '02', '03', '04', '05', '06', '07', '09', '10' ]
    train: [ '04' ]
    validation: [ '08' ]
    test: ['11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21']
    num_points: 180000
    max_range: 50.
    dataset_norm: False
    std_axis_norm: False

##Training
train:
    n_gpus: 1
    num_workers: 4
    max_epoch: 10
    lr: 0.0002
    batch_size: 2
    decay_lr: 1.0e-4

##Network
model:
    alpha_noise: 3
    repeats: [5, 8, 12, 15]
