experiment:
    id: Refine_Up6

##Data
data:
    data_dir: './KITTI_Odometry/'
    resolution: 0.05
    dataloader: 'KITTI'
    split: 'train'
    train: [ '00', '01', '02', '03', '04', '05', '06', '07', '09', '10' ]
    validation: [ '08' ]
    test: ['11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21']
    scan_window: 40
    num_points: 180000

##Training
train:
    n_gpus: 1
    num_workers: 4
    max_epoch: 5
    lr: 0.0005
    batch_size: 2
    decay_lr: 1.0e-4
    mode: 'refine'
    up_factor: 6


##Network
model:
    beta: 1
    n2c_ckpt: ./path